name: diffusion_env
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - --extra-index-url https://developer.intel.com/ipex-whl-stable-xpu
    - decorator
    - torch==2.0.1a0
    - torchvision==0.15.2a0
    - intel_extension_for_pytorch==2.0.110+xpu
    - accelerate
    - transformers
    - diffusers
    - validators
